[build]
  functions = "functions"   # Cambiar de funciones a functions

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"   # Cambiar de servidor a server
  status = 200
  force = true
